# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 111, 20))
        self.label_2.setObjectName("label_2")
        self.labelAnswer = QtWidgets.QLabel(Dialog)
        self.labelAnswer.setGeometry(QtCore.QRect(30, 260, 341, 20))
        self.labelAnswer.setText("")
        self.labelAnswer.setObjectName("labelAnswer")
        self.lineEditOne = QtWidgets.QLineEdit(Dialog)
        self.lineEditOne.setGeometry(QtCore.QRect(160, 20, 111, 20))
        self.lineEditOne.setObjectName("lineEditOne")
        self.lineEditTwo = QtWidgets.QLineEdit(Dialog)
        self.lineEditTwo.setGeometry(QtCore.QRect(160, 70, 111, 20))
        self.lineEditTwo.setObjectName("lineEditTwo")
        self.pushButtonPlus = QtWidgets.QPushButton(Dialog)
        self.pushButtonPlus.setGeometry(QtCore.QRect(70, 120, 31, 23))
        self.pushButtonPlus.setObjectName("pushButtonPlus")
        self.pushButtonMinus = QtWidgets.QPushButton(Dialog)
        self.pushButtonMinus.setGeometry(QtCore.QRect(140, 120, 31, 23))
        self.pushButtonMinus.setObjectName("pushButtonMinus")
        self.pushButtonTimes = QtWidgets.QPushButton(Dialog)
        self.pushButtonTimes.setGeometry(QtCore.QRect(220, 120, 31, 23))
        self.pushButtonTimes.setObjectName("pushButtonTimes")
        self.pushButtonDivide = QtWidgets.QPushButton(Dialog)
        self.pushButtonDivide.setGeometry(QtCore.QRect(300, 120, 31, 23))
        self.pushButtonDivide.setObjectName("pushButtonDivide")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter First Number"))
        self.label_2.setText(_translate("Dialog", "Enter Second Number"))
        self.pushButtonPlus.setText(_translate("Dialog", "+"))
        self.pushButtonMinus.setText(_translate("Dialog", "-"))
        self.pushButtonTimes.setText(_translate("Dialog", "x"))
        self.pushButtonDivide.setText(_translate("Dialog", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
